### ISSUE TITLE
pb after upgrade from ruby 1.8.3 to 1.9.3

### ISSUE THREAD

**Issue by pydubreucq** [jzaiat/redshares#8]
Hi,
I've made a debian update to Wheezy
And When I want to add a shares, I've this error in production.log

```
Started GET "/redshares/new?object_id=1138&object_type=issue" for \172.18.0.11 at 2013-11-26 22:49:19 +0100
Processing by RedsharesController#new as JS
  Parameters: {"object_id"=>"1138", "object_type"=>"issue"}
  Current user: pydubreucq (id=4)
  Rendered plugins/redshares/app/views/redshares/_new.html.erb (30.3ms)
  Rendered plugins/redshares/app/views/redshares/new.js.erb (32.7ms)
Completed 500 Internal Server Error in 83ms

ActionView::Template::Error (undefined method `id' for nil:NilClass):
    18:                  :project_id => @project) }')" %>
    19: 
    20:   <div id="users_for_redshare">
    21:     <%= principals_check_box_tags 'redshare[user_ids][]', (redshared ? redshared.addable_redshare_users : nil) %>
    22:   </div>
    23:   
    24:   <div id="roles_for_redshare">
  app/helpers/application_helper.rb:320:in `block in principals_check_box_tags'
  app/helpers/application_helper.rb:319:in `each'
  app/helpers/application_helper.rb:319:in `principals_check_box_tags'
```

Do you have an idea ?

Bye
